// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://smuihzzhawtygbfbxjza.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNtdWloenpoYXd0eWdiZmJ4anphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NDU1MTcsImV4cCI6MjA2MDEyMTUxN30.5448SCKR0t3CdzNCTQ5oh0_1uUXYfni3S0GO7-5wF1M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);